name: FTP Deploy

on:
  push:
    branches:
      - production

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2.3.2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./www/party.security/
